---
title: "Chapter_9_textbook"
author: "Lin Zhang"
date: "9/25/2019"
output: 
  html_document: 
    keep_md: yes
---

```{r}
library(rethinking)
```


```{r Metropolis Algorithm}
num_weeks <- 1e5
positions <- rep(0,num_weeks)
current <- 10
for (i in 1:num_weeks){
  positions[i] <- current  
  proposal <- current+ sample(c(-1,1),size = 1) #symmetric assumption
  if (proposal < 1) proposal <- 10
  if (proposal > 10) proposal <- 1
  prob_move <- proposal/current
  current <- ifelse(runif(1) < prob_move, proposal, current)
}
```

```{r High Dimensional Sadness ???}
D <- 10
T <- 1e3
Y <- rmvnorm(T, rep(0,D),diag(D))
rad_dist <- function(Y)sqrt(sum(Y^2))
Rd <- sapply(1:T,function(i)rad_dist(Y[i,]))
dens(Rd)
```

#9.4 Easy HMC: ULAM
```{r ruggedness ~ GDP ~ continent example}
#HMC Step01: variable transformation
library(rethinking)
data(rugged)
d <- rugged
d$log_gdp <- log(d$rgdppc_2000)
dd <- d[complete.cases(d$rgdppc_2000),]
dd$log_gdp_std <- dd$log_gdp/mean(dd$log_gdp) #why different standardization procedure
dd$rugged_std <- dd$rugged/max(dd$rugged)
dd$cid <- ifelse(dd$cont_africa==1,1,2)
```

```{r fit interaction model between ruggedness and continent using quap}
m8.5 <- quap(
  alist(
    log_gdp_std ~ dnorm(mu,sigma),
    mu <- a[cid]+b[cid]*(rugged_std-0.215),
    a[cid] ~ dnorm(1,0.1),
    b[cid] ~ dnorm(0,0.3),  # why 0.3?
    sigma ~ dexp(1)
  ),data = dd
)
precis(m8.5,depth = 2)
```
# fit the model using HMC
```{r clean data list}
# get whatever non-Gaussian shape it has
# HMC Step2: clean data list with only the variables you gonna use
dat_slim <- list(
  log_gdp_std=dd$log_gdp_std,
  rugged_std=dd$rugged_std,
  cid=as.integer(dd$cid)
)
str(dat_slim)
```

```{r sample from posterior}
library(rstan)
m9.1 <- ulam(
  alist(
    log_gdp_std ~ dnorm(mu,sigma),
    mu <- a[cid]+b[cid]*(rugged_std-0.215),
    a[cid] ~ dnorm(1,0.1),
    b[cid] ~ dnorm(0,0.3),
    sigma ~ dexp(1)
  ),data = dat_slim,chains = 1
)
```

```{r}
precis(m9.1,depth = 2)
       
```

```{r run it in parallel}
m9.1 <- ulam(
  alist(
    log_gdp_std ~ dnorm(mu,sigma),
    mu <- a[cid]+b[cid]*(rugged_std-0.215),
    a[cid] ~ dnorm(1,0.1),
    b[cid] ~ dnorm(0,0.3),
    sigma ~ dexp(1)
  ),data = dat_slim,chains = 4,cores = 4,iter = 1000
)
```

```{r}
m9.2 <- ulam(
  alist(
    log_gdp_std ~ dnorm(mu,sigma),
    mu <- a[cid]+b[cid]*(rugged_std-0.215),
    a[cid] ~ dnorm(1,0.1),
    b[cid] ~ dnorm(0,0.3),
    sigma ~ dexp(1)
  ),data = dat_slim,chains = 2,cores = 2,iter = 1000
)
```

```{r}
precis(m9.1,2)
```

##9.4.4 Visualization
```{r}
pairs(m9.1)
```
## Visualization for diagnostics
```{r}
traceplot(m9.1)
```

```{r}
trankplot(m9.1,n_cols=2)
```

