---
title: "Chapter10_textbook"
author: "Lin Zhang"
date: "10/24/2019"
output: 
  html_document: 
    keep_md: yes
---

```{r}
library(rethinking)
```

## Gausian
```{r creat possible distribution of pebbles bucket experiment}
p <- list()
p$A <- c(0,0,10,0,0)
p$B <- c(0,1,8,1,0)
p$C <- c(0,2,6,2,0)
p$D <- c(1,2,4,2,1)
p$E <- c(2,2,2,2,2)
```

```{r normalize each to form a probability distribution}
p_norm <- lapply(p,function(q) q/sum(q))
```

```{r info entropy pf probability distributions}
(H <- sapply(p_norm,function(q) -sum(ifelse(q==0,0,q*log(q)))))
```

```{r logarithm of number of ways each distribution can be realized, then divide by 10}
ways <- c(1,90,1260,37800,113400)
(logwayspp <- log(ways)/10)
```
## Binomial
```{r compute binomial distribution based on expected value}
p <- 0.5
(A <- c( (1-p)^2, p*(1-p),(1-p)*p,p^2))
```


```{r build list of the candidate distributions}
p <- list()
p[[1]] <- c(1/4,1/4,1/4,1/4)
p[[2]] <- c(2/6,1/6,1/6,2/6)
p[[3]] <- c(1/6,2/6,2/6,1/6)
p[[4]] <- c(1/8,4/8,2/8,1/8)
# compute expected value of each
sapply(p,function(p)sum(p*c(0,1,1,2)))
```

```{r compute entropy of each distribution}
sapply(p,function(p)-sum(p*log(p)))
```

```{r compute binomial distribution with another expected value}
p <- 0.7
(A <- c( (1-p)^2, p*(1-p),(1-p)*p,p^2))
```

```{r compute entropy of above distribution}
-sum(A*log(A))
```

```{r simulate random probability distributions with specified expected value} 
# ?generates a random distribution with expected value G and then returns its entropy alongwith the distribution
sim.p <- function(G=1.4) { 
  x123 <- runif(3) 
  x4 <- ( (G)*sum(x123)-x123[2]-x123[3] )/(2-G) 
  z <- sum( c(x123,x4) ) 
  p <- c( x123 , x4 )/z 
  list( H=-sum( p*log(p) ) , p=p )
}
```

```{r simulate random distributions with fixed expected value}
# simulate to generate random distributions for 1e5 times and plot resulting entropies
H <- replicate(1e5,sim.p(1.4))
dens(as.numeric(H[1,]),adj = 0.1)
```

```{r split entropies and distributions}
entropies <- as.numeric(H[1,])
distributions <- H[2,]
```

```{r distribution with largest observed entropy}
max(entropies)
distributions[which.max(entropies)]
```

