---
title: "Chapter8_textbook"
author: "Lin Zhang"
date: "2019/9/21"
output: 
  html_document: 
    keep_md: yes
---

```{r setup}
library(rethinking)
data("rugged")
d <- rugged
```

```{r}
# make log verison of outcome
d$log_gdp <- log(d$rgdppc_2000)
# extract countries with GDP data
dd <- d[complete.cases(d$rgdppc_2000),]
nrow(d)
nrow(dd)
# rescale variables
dd$log_gdp_std <- dd$log_gdp/mean(dd$log_gdp)
dd$rugged_std <- dd$rugged/max(dd$rugged)
# split countries into Africa and not-Africa
d.A1 <- dd[dd$cont_africa==1,]
d.A0 <- dd[dd$cont_africa==0,]
```

```{r model for Africa}
m8.1 <- quap(
  alist(
    log_gdp_std ~ dnorm(mu,sigma),
    mu <- a+b*(rugged_std-0.215),
    a ~ dnorm(1,1),
    b ~ dnorm(0,1),
    sigma ~ dexp(1)
  ), data=d.A1
)
```

```{r prior prediction}
set.seed(7)
prior <- extract.prior(m8.1)
# set up the plot dimensions
plot(NULL, xlim=c(0,1), ylim=c(0.5,1.5),xlab="ruggedness",ylab="log GDP")
abline(h=min(dd$log_gdp_std),lty=2)
abline(h=max(dd$log_gdp_std),lty=2)
# draw 50 lines from the prior
rugged_seq <- seq(from=-0.1,to = 1.1,length.out = 30)
mu <- link(m8.1, post=prior, data = data.frame(rugged_std=rugged_seq))
for (i in 1:50)lines(rugged_seq,mu[i,],col=col.alpha("black",0.3))
```

```{r}
sum(abs(prior$b) > 0.6)/length(prior$b)
```

```{r tighten the prior}
m8.1 <- quap(
  alist(
    log_gdp_std ~ dnorm(mu,sigma),
    mu <- a+b*(rugged_std-0.215),
    a ~ dnorm(1,0.1),
    b ~ dnorm(0,0.3),
    sigma ~ dexp(1)
  ), data=d.A1
)
```

```{r}
prior <- extract.prior(m8.1)
# set up the plot dimensions
plot(NULL, xlim=c(0,1), ylim=c(0.5,1.5),xlab="ruggedness",ylab="log GDP")
abline(h=min(dd$log_gdp_std),lty=2)
abline(h=max(dd$log_gdp_std),lty=2)
# draw 50 lines from the prior
rugged_seq <- seq(from=-0.1,to = 1.1,length.out = 30)
mu <- link(m8.1, post=prior, data = data.frame(rugged_std=rugged_seq))
for (i in 1:50)lines(rugged_seq,mu[i,],col=col.alpha("black",0.3))
```

```{r non-African nations}
m8.2 <- quap(
  alist(
    log_gdp_std ~ dnorm(mu,sigma),
    mu <- a+b*(rugged_std-0.215),
    a ~ dnorm(1,0.1),
    b ~ dnorm(0,0.25),
    sigma ~ dexp(1)
  ), data=d.A0
)
```

```{r inspect both models}
precis(m8.1)
precis(m8.2)
```
# Model for both African and non-African nations
```{r no index variable}
m8.3 <- quap(
  alist(
    log_gdp_std ~ dnorm(mu,sigma),
    mu <- a+b*(rugged_std-0.215),
    a ~ dnorm(1,0.1),
    b ~ dnorm(0,0.3),
    sigma ~ dexp(1)
  ), data=dd
)
```

```{r a model allow nations of different catagory to have different intercepts}
# make variable to index Africa (1) or not (2)
dd$cid <- ifelse(dd$cont_africa==1,1,2)
m8.4 <- quap(
  alist(
    log_gdp_std ~ dnorm(mu,sigma),
    mu <- a[cid]+b*(rugged_std-0.215),
    a[cid]~ dnorm(1,0.1),
    b ~ dnorm(0,0.3),
    sigma ~ dexp(1)), data=dd
)
```

```{r}
compare(m8.3,m8.4)
```

```{r}
plot(precis(m8.4,depth=2))
```

```{r plot the posterior distribution}
rugged.seq <- seq(from=-0.1,to=1.1,length.out = 30)
# compute mu over samples, fixing cid=2
mu.NotAfrica <- link(m8.4, data = data.frame(cid=2, rugged_std=rugged.seq))
# compute mu over samples, fixing cid=1
mu.Africa <- link(m8.4, data = data.frame(cid=1, rugged_std=rugged.seq))
# summarize to means and intervals
mu.NotAfrica_mu <- apply(mu.NotAfrica,2,mean)
mu.NotAfrica_ci <- apply(mu.NotAfrica,2,PI,prob=0.97)
mu.Africa_mu <- apply(mu.Africa,2,mean)
mu.Africa_ci <- apply(mu.Africa,2,PI,prob=0.97)
```
# add interaction by index the slope
```{r}
m8.5 <- quap(
  alist(
    log_gdp_std ~ dnorm(mu,sigma),
    mu <- a[cid]+b[cid]*(rugged_std-0.215),
    a[cid] ~ dnorm(1,0.1),
    b[cid] ~ dnorm(0,0.3),
    sigma ~ dexp(1)
  ),data = dd
)
```

```{r}
precis(m8.5,depth = 2)
```

```{r}
compare(m8.3,m8.4,m8.5)
```
# examine point-wise WAIC
```{r}
# see which nations(pionts) are sensitive and accounting for posterior variance
waic_list <- WAIC(m8.5,pointwise = TRUE)
```
# Plotting the interaction
```{r}
# plot Africa -cid=1
plot(d.A1$rugged_std, d.A1$log_gdp_std, pch=16, col=rangi2,
     xlab="ruggedness(standardized)",ylab="log GDP (as proportion of mean)",
     xlim=c(0,1))
mu <- link(m8.5, data = data.frame(cid=1, rugged_std=rugged_seq))
mu_mean <- apply(mu,2,mean)
mu_ci <- apply(mu,2,PI,prob=0.97)
lines(rugged_seq, mu_mean, lwd=2)
shade(mu_ci,rugged_seq,col= col.alpha(rangi2,0.3))
mtext("African nations")

# plot non-African - cid=2
plot(d.A0$rugged_std, d.A0$log_gdp_std, pch=1, col="black", xlab="ruggedness(standardized)", ylab="log GDP (as proportion of mean)", xlim=c(0,1))
mu <- link(m8.5, data = data.frame(cid=2, rugged_std=rugged_seq))
mu_mean <- apply(mu,2,mean)
mu_ci <- apply(mu,2,PI,prob=0.97)
lines(rugged_seq, mu_mean, lwd=2)
shade(mu_ci,rugged_seq)
mtext ("Non-African nations")
```

# symmetry of interactions
```{r reverse interpretation}
# the association of being in Africa with log GDP dpends upon terrain ruggedness
rugged_seq <- seq(from=-0.2, to=1.2, length.out = 30)
muA <- link(m8.5, data = data.frame(cid=1, rugged_std=rugged_seq))
muN <- link(m8.5, data = data.frame(cid=2,rugged_std=rugged_seq))
delta <- muA-muN
```

# Continuous Interactions
```{r}
library(rethinking)
data(tulips)
d <- tulips
str(d)
```
## variable transformation and scale
```{r pre-center variable and scale outcome by its maximum}
d$blooms_std <- d$blooms/max(d$blooms)
d$water_cent <- d$water-mean(d$water)
d$shade_cent <- d$shade-mean(d$shade)
```

```{r examine the prior}
# initial setting
# a ~ Normal(0.5,1)
# bw ~ Normal(0,1) # alow 
# as mean of blooms/max(blooms), a should be between zero and one
a <- rnorm(1e4,0.5,1)
sum(a<0 | a >1)/length(a)
a <- rnorm(1e4,0.5,0.25)
sum(a<0 | a >1)/length(a)

```

```{r}
m8.6 <- quap(
  alist(
    blooms_std ~ dnorm(mu,sigma),
    mu <- a + bw*water_cent+bs*shade_cent,
    a ~ dnorm(0.5,0.25),
    bw ~ dnorm(0,0.25),
    bs ~ dnorm(0,0.25),
    sigma ~ dexp(1)
    ), data = d
)
```

```{r add interaction variable}
m8.7 <- quap(
  alist(
    blooms_std ~ dnorm(mu,sigma),
    mu <- a+bw*water_cent+bs*shade_cent+bws*water_cent*shade_cent,
    a ~ dnorm(0.5,0.25),
    bw ~ dnorm(0,0.25),
    bs ~ dnorm(0,0.25),
    bws ~ dnorm(0,0.25), # largest effect is bw+bwsSi=0, Si max is 1 in this case
    sigma ~ dexp(1)
  ),data = d
)
```

```{r triptych plot posterior predictions for non-interaction built in model}
par(mfrow=c(1,3))
  for (s in -1:1){
    idx <- which(d$shade_cent==s)
    plot(d$water_cent[idx], d$blooms_std[idx], xlim=c(-1,1),ylim=c(0,1),xlab="water", ylab="blooms",pch=16, col=rangi2)
    mu <- link(m8.6,data = data.frame(shade_cent=s, water_cent=-1:1))
    for (i in 1:20)lines(-1:1,mu[i,],col=col.alpha("black",0.3))
  }
```

```{r triptych plot posterior predictions for interaction built in model}
par(mfrow=c(1,3))
  for (s in -1:1){
    idx <- which(d$shade_cent==s)
    plot(d$water_cent[idx], d$blooms_std[idx], xlim=c(-1,1),ylim=c(0,1),xlab="water", ylab="blooms",pch=16, col=rangi2)
    mu <- link(m8.7,data = data.frame(shade_cent=s, water_cent=-1:1))
    for (i in 1:20)lines(-1:1,mu[i,],col=col.alpha("black",0.3))
  }
```

```{r symmetrical interaction parameter}
# put shade on horizontal line
par(mfrow=c(1,3))
  for (w in -1:1){
    idx <- which(d$water_cent==w)
    plot(d$shade_cent[idx], d$blooms_std[idx], xlim=c(-1,1),ylim=c(0,1),xlab="shade", ylab="blooms",pch=16, col=rangi2)
    mu <- link(m8.6,data = data.frame(water_cent=w, shade_cent=-1:1))
    for (i in 1:20)lines(-1:1,mu[i,],col=col.alpha("black",0.3))
  }

par(mfrow=c(1,3))
  for (w in -1:1){
    idx <- which(d$water_cent==w)
    plot(d$shade_cent[idx], d$blooms_std[idx], xlim=c(-1,1),ylim=c(0,1),xlab="shade", ylab="blooms",pch=16, col=rangi2)
    mu <- link(m8.7,data = data.frame(water_cent=w, shade_cent=-1:1))
    for (i in 1:20)lines(-1:1,mu[i,],col=col.alpha("black",0.3))
  }
```

```{r plot prior predictions}
set.seed(7)
prior <- extract.prior(m8.6)
```

