=---
title: "Chapter12_textbook"
author: "Lin Zhang"
date: "11/11/2019"
output: 
  html_document: 
    keep_md: yes
---

```{r}
# beta distribution
pbar <- 0.7 # average probability
theta <- 2 # shapre parameter, >2 distri of probabilities more concentrated
curve(dbeta2(x,pbar,theta),from = 0,to = 1,xlab = "probability", ylab = "Density")
```
# fit betabinomial to UCBadmit, in which adm rate vary by department
```{r}
library(rethinking)
data("UCBadmit")
d <- UCBadmit
d$gid <- ifelse(d$applicant.gender=="male",1L,2L)
dat <- list(A=d$admit, N=d$applications, gid=d$gid)
m12.1 <- ulam(
  alist(
    A ~ dbetabinom(N,pbar,theta)，
    logit(pbar) <- a[gid],
    a[gid] ~ dnorm(0,1.5),
    theta ~ dexp(1)
  ),data=dat,chains=4
)
```

# compute contrast of two genders
```{r}
post <- extract.samples(m12.1)
post$da <- post$a[,1]-post$a[,2]
precis(post,depth = 2)
```

```{r sample unobserved intercept for each combination of department and gender}
# unobserved intercepts are sampled from a beta distribution with mean pi and dispersion theta, plot what the beta distribution looks like
gid <- 2
# draw posterior mean beta distribution
curve(dbeta2(x,mean(logistic(post$a[,gid])),mean(post$theta)),from = 0, to = 1, ylab = "Density",xlab = "probability admit", ylim=c(0,3),lwd=2)
# draw 50 beta distributions sampled from posterior
for (i in 1:50){
  p <- logistic(post$a[i,gid])
  theta <- post$theta[i]
  curve(dbeta2(x,p,theta), add = TRUE, col=col.alpha("black",0.2))
}
mtext("distribution of female admission rate")
```

```{r}
# how the beta distribution of probabilities of admission influences predicted counts of applications admitted
# posterior validation check
postcheck(m12.1)
```

