---
title: "Chapter3_HW"
author: "Lin Zhang"
date: "4/19/2019"
output: 
  html_document: 
    keep_md: yes
---

```{r}
p_grid <- seq(from=0, to=1, length.out=1000)
prior <- rep (1,1000)
likelihood <- dbinom (6, size = 9, prob=p_grid)
posterior <- likelihood* prior
posterior <- posterior/sum(posterior)
set.seed(100)
samples <- sample(p_grid, prob = posterior, size = 1e4, replace = TRUE)
hist(samples)
```

## 3E1
```{r}
#str(p_grid)
#str(samples)
#length(samples)
sum(samples <0.2)/length(samples)
```
## 3E2
```{r}
sum(samples >0.8)/length(samples)
```

## 3E3
```{r 3E3}
sum (samples > 0.2 & samples <0.8) / length(samples)
```
## 3E4
```{r 3E4}
quantile(samples,0.2)
```
## 3E5
```{r 3E5}
quantile(samples,0.8)
```
## 3E6
```{r 3E6}
library(rethinking)
HPDI(samples, prob = 0.66)
```
## 3E7
```{r 3E7}
library(rethinking)
PI(samples, prob = 0.66)
```
## 3M1
```{r 3M1}
p_grid <- seq(from=0, to=1, length.out=1000)
prior <- rep (1,1000)
likelihood2 <- dbinom (8, size = 15, prob=p_grid)
posterior2 <- likelihood2* prior
posterior2 <- posterior2/sum(posterior2)

```

## 3M2
```{r 3M2}
set.seed(100)
samples2 <- sample(p_grid, prob = posterior2, size = 1e4, replace = TRUE)
hist(samples2)
library(rethinking)
HPDI(samples, prob = 0.90)
```
## 3M3
```{r 3M3}
w2 <- rbinom(1e4, size = 15,prob = samples2)
simplehist(w2)
sum(w2==8)/length(w2)

```

## 3M4
```{r 3M4}
w3 <- rbinom(1e4, size = 9, prob = samples2)
simplehist(w3)
sum(w3==6)/length(w3)
```

## 3M5
```{r}
p_grid3 <- seq(from=0, to=1, length.out = 1000)
#prior3 <- rep(c(0,1),each=500)
library(dplyr)
prior3 <- rep(1,length(p_grid)) %>% ifelse(p_grid < .5, 0, .)
likelihood3 <- dbinom(8,size = 15, prob = p_grid3)
plot(likelihood3)
posterior3 <- likelihood3*prior3
posterior3 <- posterior3/sum(posterior3)
plot(posterior3)
samples3 <- sample(posterior3,size = 1e4,replace = TRUE,prob = posterior3)
hist(samples3)
HPDI(samples3,prob = 0.9)
w6 <- rbinom(1e4,size = 9,prob = 0.7)
wp <- rbinom(1e4,size = 9,prob = samples3)
simplehist(w6)
simplehist(wp)
sum(wp==6)/length(w3)
#if it helps, compare inferences(using both priors)to the true value p=0.7
```

## Hard
```{r}
birth1 <- c(1,0,0,0,1,1,0,1,0,1,0,0,1,1,0,1,1,0,0,0,1,0,0,0,1,0, 0,0,0,1,1,1,0,1,0,1,1,1,0,1,0,1,1,0,1,0,0,1,1,0,1,0,0,0,0,0,0,0, 1,1,0,1,0,0,1,0,0,0,1,0,0,1,1,1,1,0,1,0,1,1,1,1,1,0,0,1,0,1,1,0, 1,0,1,1,1,0,1,1,1,1)
birth2 <- c(0,1,0,1,0,1,1,1,0,0,1,1,1,1,1,0,0,1,1,1,0,0,1,1,1,0, 1,1,1,0,1,1,1,0,1,0,0,1,1,1,1,0,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1, 1,1,1,0,1,1,0,1,1,0,1,1,1,0,0,0,0,0,0,1,0,0,0,1,1,0,0,1,0,0,1,1, 0,0,0,1,1,1,0,0,0,0)
library(rethinking) 
data(homeworkch3)
sum(birth1) + sum(birth2)
```
# 3H1
```{r}
p_grid <- seq(from=0, to=1, length.out = 1000)
prior <- rep(1,1000)
total_boy <- sum(birth1)+sum(birth2)
likelihood <- dbinom(total_boy, size = 200, prob = p_grid ) 
posterior <- likelihood*prior
posterior <- posterior/sum(posterior)
plot(p_grid, posterior)
p_grid[which.max(posterior)]
```

## 3H2
```{r}
set.seed(100)
samples <- sample(p_grid, prob = posterior, size = 1e4, replace = TRUE)
library(rethinking)
HPDI(samples,c(0.5,0.89,0.97))

```

## 3H3
```{r}
simulation_p_birth <- rbinom(1e4, size = 200,prob = samples)
simplehist(simulation_p_birth)
mean(simulation_p_birth)
median(simulation_p_birth)


```

## 3H4
```{r}
p_grid <- seq(from=0, to=1, length.out = 1000)
prior <- rep(1,1000)
likelihood_1stb <- dbinom(sum(birth1), size = 100, prob = p_grid ) 
posterior_1stb <- likelihood_1stb*prior
posterior_1stb <- posterior_1stb/sum(posterior_1stb)
samples_1stb <- sample(p_grid, prob = posterior_1stb,size = 1e4, replace = TRUE)
random_p_1stb <- rbinom(1e4, size = 100, prob = samples_1stb)
den//
  s(random_p_1stb)

```

## 3H5
```{r}
p_grid <- seq(from=0, to=1, length.out = 1000)
prior <- rep(1,1000)


```

